### ISSUE TITLE
trying to get UIbutton to make gameplaying = true

### ISSUE THREAD

**Issue by nickburum** [txaiwieser/TWSpriteKitUtils#10]
my issue is Thread 1: signal SIGABRT

have this is gameviewcontroller.swift
var gameplaying = true

 @IBAction func Start(_ sender: Any) {
        gameplaying = true
    }

wanting this to in turn activate my if statement in my game scene.swift
here that code 
if gameplaying == true {
            addChild(PigSprite!)
            BirdSprite?.size = CGSize(width: 60, height: 70 )
            BirdSprite?.position = CGPoint(x:220, y:0)
            SpikeSprite?.size = CGSize(width: 80, height: 80 )
            SpikeSprite?.position = CGPoint(x:500, y:-98)
            SpikeSprite1?.size = CGSize(width: 80, height: 80 )
            SpikeSprite1?.position = CGPoint(x:300, y:-98)
        }

**Comment by txaiwieser** [comment]
Hey, can you describe a little more what you're trying to do?

You can also enable breakpoints to easily debug your issues.
http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions

**Comment by nickburum** [comment]
im trying to to get a play button from my main storyboard to activate code from my game scene.swift code

**Comment by nickburum** [comment]
> im trying to to get a play button from my main storyboard to activate code from my game scene.swift code

forgot to add when I press the button the app crashed and says "Thread 1: signal SIGABRT"

**Comment by txaiwieser** [comment]
This buttons are for use inside a SKScene, not in a Storyboard.

You can debug your crash using the link I sent you. http://blog.manbolo.com/2012/01/23/xcode-tips-1-break-on-exceptions

You can follow the examples on this project to see how you can use a TWButton inside a SKScene!

If you need something else this comment here. Just going to close as is not a Lib issue!

**Comment by nickburum** [comment]
thx
